### ISSUE TITLE
Using for Cpp

### ISSUE THREAD

**Issue by khanhhoaa19** [openslide/openslide-winbuild#134]
Can I use openslide-winbuild for cpp?

**Comment by bgilbert** [comment]
Could you explain what you're trying to accomplish?

**Comment by khanhhoaa19** [comment]
I cloned this repo, downloaded Docker from https://www.docker.com/, and ran the command "docker run -ti --rm -v $PWD:/work -w /work ghcr.io/openslide/winbuild-builder./build.sh bdist" in the command line. After the build is done, I cannt include <openslide.h>. Can you guide me to build and use it for cpp on Windows?

**Comment by bgilbert** [comment]
`build.sh` creates a ZIP file containing the library (32-bit or 64-bit depending whether you passed `-m64`) and the header files.  You'll need to unpack the ZIP file and add the library and headers to the appropriate search paths in your IDE.

Note that most users shouldn't need to build from source.  Stable binaries are available [here](https://openslide.org/download/#windows-binaries) and nightly builds from Git are available [here](https://openslide.org/builds/windows/).
