### ISSUE TITLE
Matlab crashing when run openslide_open(Trestle .tf whole-slide-image).m

### ISSUE THREAD

**Issue by CindyQi** [openslide/openslide-winbuild#14]
Hi 

Matlab crashed consecutively when run openslide_open.m by loading Trestle .tif format whole-slide image. 

I tried different versions of openslide-win64 (such as openslide-win64-20171122,  openslide-win64-20171123-nightly,  openslide-win64-20161204), SAME ISSUE.

Please help me for this issue.

Thank you very much.
Xin

**Comment by bgilbert** [comment]
The `bin` directory of the openslide-win64 distribution includes a program, `openslide-show-properties.exe`.  If you cd into that `bin` directory from the Windows command prompt and run

```
openslide-show-properties c:\path\to\Trestle\file.tif
```

does it produce output?

**Comment by CindyQi** [comment]
The output is


Not a file that OPenSlide can recognize.


Xin

________________________________

**Comment by bgilbert** [comment]
Could you set the `OPENSLIDE_DEBUG` environment variable to `detection` and rerun that command?

**Comment by CindyQi** [comment]
May you please tell where to set the OPENSLIDE_DEBUG environment variable to detection?


Then return the command below?

openslide-show-properties c:\path\to\Trestle\file.tif


Thanks a lot

Xin


________________________________

**Comment by bgilbert** [comment]
At the `cmd.exe` prompt, type:

```
set OPENSLIDE_DEBUG=detection
openslide-show-properties c:\path\to\Trestle\file.tif
```

**Comment by bgilbert** [comment]
Closing due to lack of response.
