### ISSUE TITLE
stuck at Fetching ffi

### ISSUE THREAD

**Issue by zhanghaoyue** [openslide/openslide-winbuild#16]
While running ./build.sh bdist
it stuck at 
Fetching ffi...

I wonder what is going on here..?

**Comment by bgilbert** [comment]
Can your build machine reach `ftp://sourceware.org/`?

**Comment by zhanghaoyue** [comment]
oh I cannot! 
and after one night running I got this:
Failed: ${wget} -P tar "$url" (line 280)
