### ISSUE TITLE
"[WinError 126] The specified module could not be found" when importing openslide

### ISSUE THREAD

**Issue by nd26** [openslide/openslide-winbuild#18]
Hi,

On importing the module, I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/HistopathologicalAnalysis/read_scn_images/scn_image_reader.py", line 3, in <module>
    import openslide
  File "C:\Users\User\Anaconda3\lib\site-packages\openslide\__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "C:\Users\User\Anaconda3\lib\site-packages\openslide\lowlevel.py", line 41, in <module>
    _lib = cdll.LoadLibrary('libopenslide-0.dll')
  File "C:\Users\User\Anaconda3\lib\ctypes\__init__.py", line 428, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\User\Anaconda3\lib\ctypes\__init__.py", line 350, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

What could be the issue?

**Comment by bgilbert** [comment]
Is the OpenSlide DLL in your library search path?

**Comment by Albelt** [comment]
Hi, I got the same error?
Can you tell more details to solve this problem?

> Is the OpenSlide DLL in your library search path?

**Comment by LiamTTT** [comment]
Try this answer https://stackoverflow.com/questions/43987081/openslide-python-import-error

**Comment by bgilbert** [comment]
Note that that StackOverflow question is for error 127, not 126, as the accepted answer points out.

You must install the [OpenSlide Windows binaries](https://openslide.org/download/#windows-binaries) and ensure that they are in the [DLL search path](https://docs.microsoft.com/en-us/windows/desktop/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications).

**Comment by xhm1014** [comment]
after downloading the OpenSlide Windows binaries, you need to add the 'bin' folder to your environmental path. For more see: https://github.com/xhm1014/openslide-python/blob/master/README.md

**Comment by gautamworks** [comment]
Hi I face the same issue

**Comment by gautamworks** [comment]
Ya, I solved it, download win-32 bit binaries(not -64), it will work for 64 bit windows also, and copy all .dll files from bin and place it in the python37-32 folder, this is one of your environment folders, as I am using python 3.7 so default name is python37-32, check your python version for name. 
To know the exact location of the environment from python.
Type a small code:
import sys
for p in sys.path:
      print(p)

**Comment by bgilbert** [comment]
Locking issue to avoid proliferation of support requests.
