### ISSUE TITLE
Python.exe Entry point not found

### ISSUE THREAD

**Issue by anburiyan** [openslide/openslide-winbuild#19]
Hi All,

I have installed OpenSlide and openslide-python both are latest version. I am getting below attached screen error message when importing openslide.

Note:
I have gave the openslide binaries path to system variable.

![image](https://user-images.githubusercontent.com/13828286/40192958-6f42e484-5a23-11e8-97fc-94061ecbc1a0.png)

Anybody, can help me on this?

Thanks,

**Comment by bgilbert** [comment]
Try with vanilla Python rather than Anaconda.  We've sometimes seen problems where Anaconda installations include their own copy of one of the libraries shipped with the OpenSlide Windows binaries, and then the wrong copy gets used.

**Comment by anburiyan** [comment]
@bgilbert - Thanks for the reply.

It get resolved in another way by simply copy openslide binaries all dlls to system32 folder.
