### ISSUE TITLE
the prebuilt dlls fail to install due to the following error

### ISSUE THREAD

**Issue by DariusArya** [openslide/openslide-winbuild#24]
The procedure entry point iconv could not be located in the dynamic link library libxml2-2.dll
The procedure entry point iconv could not be located in the dynamic link library libiintl-8.dll

my machine is a Windows 10, 64 bit, 

I have tried all the 64 bit prebuilt libraries, new and old. 

I have tried a one 32 bit library, didn't work. 

I only have limited time to resolve this issue.

Your prompt help is deeply appreciated.

**Comment by bgilbert** [comment]
Duplicate of #21.
