### ISSUE TITLE
I fellow the guide of other auther's blog,but it also report the issue:ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by dawalisi** [openslide/openslide-winbuild#29]
when I used the openslide it reported the issue : ImportError: FileNotFoundError: Could not find module 'libopenslide-0.dll'. Try using the full path with constructor syntax.

**Comment by bgilbert** [comment]
There's not nearly enough information here to diagnose the issue.  Please describe exactly what you did and what output you received.

**Comment by dawalisi** [comment]
Please forgive me for this poor English.  Thank you for your reply.
When I call the openslide library function,some issue happened:
![image](https://user-images.githubusercontent.com/89849524/146357257-c7ce4a50-5ee6-417a-92a4-f869812eba1e.png)
I found the question from the lowlevel.py , it can't find the 'libopenslide-0.dll' 
![image](https://user-images.githubusercontent.com/89849524/146358251-b2ab6bf2-6efc-49ec-9e0c-4c2a1b9f8096.png)
I don't know how to solve this problem.

**Comment by bgilbert** [comment]
If you're using Python 3.8 or above, does this work for you?

```python
import os
with os.add_dll_directory(r'e:\Anaconda\Library\openslide-win64-20171122\bin'):
    import openslide
```

**Comment by bgilbert** [comment]
Closing due to lack of response.

**Comment by dawalisi** [comment]
> 如果您使用的是Python 3.8或更高版本，这对您有用吗？
> 
> ```python
> import os
> with os.add_dll_directory(r'e:\Anaconda\Library\openslide-win64-20171122\bin'):
>     import openslide
> ```
I solved this problem by other answers，thanks.
