### ISSUE TITLE
Consider removing support for building from Cygwin

### ISSUE THREAD

**Issue by bgilbert** [openslide/openslide-winbuild#36]
WSL is the future and should be easier to support.

(Also, Linux-based CI is broadly available, so maybe it isn't as important to support building from Windows at all?)

**Comment by jrshoare** [comment]
I have found cross-compiling from Linux using Docker to have a much lower entry barrier as a Windows developer. I forked the repo from [PathXL/openslide-winbuild](https://github.com/PathXL/openslide-winbuild) rather than use the 'official' repo to do this.

Please consider whether a Docker option should be included to allow building from Windows.

**Comment by bgilbert** [comment]
So the idea is that we'd provide a Dockerfile with the build dependencies?  Actually, yeah, that makes a lot of sense even for Linux builds.

**Comment by bgilbert** [comment]
@jrshoare Thanks for the suggestion!  https://github.com/openslide/openslide-winbuild/pull/37 adds a builder container; please try it out and report any problems.

I've posted an RFC PR in #39 to remove all support for building outside the container.

**Comment by bgilbert** [comment]
`configure` is trying to write some output to `config.log` and getting `ENOENT`, which suggests that the current directory doesn't exist (?).  By this point we've run several other `configure` scripts without issue, so it's not a generic problem.

It turns out that the libffi `configure` has some magic to create a target-specific subdirectory and rerun itself from in there (`continue configure in default builddir`).  I'm guessing that's breaking things.  Could you add `--disable-builddir` to [this line](https://github.com/openslide/openslide-winbuild/blob/8539155909ffe7be50bb46bcb81e0811375b036a/build.sh#L566) and try again?

**Comment by jrshoare** [comment]
Yes that fixed it. I now have a working build. Thanks.

**Comment by bgilbert** [comment]
Thanks for testing!  Fixes in https://github.com/openslide/openslide-winbuild/pull/44.
